version: "3.8"

networks:
  petdex-network:

services:
  api-java:
    image: ${DOCKERHUB_USERNAME}/api-java:${TAG}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    networks:
      - petdex-network
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - JWT_SECRET=${JWT_SECRET}
      - BCRYPT_SALT=${BCRYPT_SALT}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-cloud-key.json
    volumes:
      - ./uploads:/uploads 
      - ./app/google-cloud-key.json:/app/google-cloud-key.json
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "8081:6379"
    networks:
      - petdex-network
    restart: always

  api-python:
    image: ${DOCKERHUB_USERNAME}/api-python:${TAG}
    networks:
      - petdex-network
    ports:
      - "8083:8083"
    environment:
      - API_URL=http://api-java:8080
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_TTL_MINUTES=10
      - PUBSUB_TOPIC=petdex-statistic
      - PUBSUB_SUBSCRIPTION=petdex-statistic-sub
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-cloud-key.json
    volumes:
      - ./app/google-cloud-key.json:/app/google-cloud-key.json
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  web:
    image: ${DOCKERHUB_USERNAME}/petdex-web:${TAG}
    ports:
      - "8082:8082"
    environment:
      - JAVA_API_URL=http://api-java:8080
    networks:
      - petdex-network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
