from app.application.services.CheckupService import CheckupService
from app.application.services.EstatisticaService import EstatisticaService
from app.application.services.RecomendacaoService import RecomendacaoService
